export const SITE_INFO = {
  title: 'Digital Sunsets',
  description: 'Generated by Digital Sunsets L.L.C.',
};

export const PACKAGE_PRICES = {
  Starter: {
    name: 'Starter',
    description:
      'Perfect for individuals or small businesses just getting started.',
    price: 600,
    priceSpecial: 295,
    features: ['Single Page Website', 'Basic SEO', 'Custom Domain'],
  },
  Pro: {
    name: 'Pro',
    description:
      'Great for growing businesses looking to scale their online presence.',
    price: 2400,
    priceSpecial: 2095,
    features: [
      'Multi-Page Website',
      'Advanced SEO',
      'Ecommerce Capabilities',
      'Content Management System',
    ],
  },
  Enterprise: {
    name: 'Enterprise',
    description:
      'Tailored solutions for larger businesses and enterprises looking for advanced features and scalability.',
    price: 3600,
    priceSpecial: 3295,
    features: [
      'All Pro Features +',
      'Custom Solutions (Eg. Ecommerce, Blog, etc.)',
      'Dedicated Support',
      'Scalabille Infrastructure',
      'Advanced Analytics',
      'Custom Integrations',
    ],
  },
};
