/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetCompareStatViewRequest,
  GetStatViewRequest,
} from '../models/index';
import {
    GetCompareStatViewRequestFromJSON,
    GetCompareStatViewRequestToJSON,
    GetStatViewRequestFromJSON,
    GetStatViewRequestToJSON,
} from '../models/index';

export interface StatsComparePostRequest {
    getCompareStatViewRequest?: GetCompareStatViewRequest;
}

export interface StatsViewPostRequest {
    getStatViewRequest?: GetStatViewRequest;
}

/**
 * 
 */
export class StatProxyResourceApi extends runtime.BaseAPI {

    /**
     * Compare statistics of several Entities for a given time interval.
     * Compare statistics of several Entities
     */
    async statsComparePostRaw(requestParameters: StatsComparePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/stats/compare`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetCompareStatViewRequestToJSON(requestParameters['getCompareStatViewRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Compare statistics of several Entities for a given time interval.
     * Compare statistics of several Entities
     */
    async statsComparePost(requestParameters: StatsComparePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statsComparePostRaw(requestParameters, initOverrides);
    }

    /**
     * Get Entity statistics for a given time interval.
     * Get Entity statistics
     */
    async statsViewPostRaw(requestParameters: StatsViewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/stats/view`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetStatViewRequestToJSON(requestParameters['getStatViewRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get Entity statistics for a given time interval.
     * Get Entity statistics
     */
    async statsViewPost(requestParameters: StatsViewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.statsViewPostRaw(requestParameters, initOverrides);
    }

}
