/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const App = {
    Dts: 'DTS',
    ConversationalServiceCm: 'CONVERSATIONAL_SERVICE_CM',
    Stats: 'STATS'
} as const;
export type App = typeof App[keyof typeof App];


export function instanceOfApp(value: any): boolean {
    return Object.values(App).includes(value);
}

export function AppFromJSON(json: any): App {
    return AppFromJSONTyped(json, false);
}

export function AppFromJSONTyped(json: any, ignoreDiscriminator: boolean): App {
    return json as App;
}

export function AppToJSON(value?: App | null): any {
    return value as any;
}

