/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CampaignTypeFilter = {
    ConversationalService: 'CONVERSATIONAL_SERVICE'
} as const;
export type CampaignTypeFilter = typeof CampaignTypeFilter[keyof typeof CampaignTypeFilter];


export function instanceOfCampaignTypeFilter(value: any): boolean {
    return Object.values(CampaignTypeFilter).includes(value);
}

export function CampaignTypeFilterFromJSON(json: any): CampaignTypeFilter {
    return CampaignTypeFilterFromJSONTyped(json, false);
}

export function CampaignTypeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignTypeFilter {
    return json as CampaignTypeFilter;
}

export function CampaignTypeFilterToJSON(value?: CampaignTypeFilter | null): any {
    return value as any;
}

