/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CampaignPriority = {
    Interactive: 'INTERACTIVE',
    High: 'HIGH',
    Low: 'LOW'
} as const;
export type CampaignPriority = typeof CampaignPriority[keyof typeof CampaignPriority];


export function instanceOfCampaignPriority(value: any): boolean {
    return Object.values(CampaignPriority).includes(value);
}

export function CampaignPriorityFromJSON(json: any): CampaignPriority {
    return CampaignPriorityFromJSONTyped(json, false);
}

export function CampaignPriorityFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignPriority {
    return json as CampaignPriority;
}

export function CampaignPriorityToJSON(value?: CampaignPriority | null): any {
    return value as any;
}

