/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CampaignManagement } from './CampaignManagement';
import {
    CampaignManagementFromJSON,
    CampaignManagementFromJSONTyped,
    CampaignManagementToJSON,
} from './CampaignManagement';
import type { CampaignType } from './CampaignType';
import {
    CampaignTypeFromJSON,
    CampaignTypeFromJSONTyped,
    CampaignTypeToJSON,
} from './CampaignType';
import type { EntityState } from './EntityState';
import {
    EntityStateFromJSON,
    EntityStateFromJSONTyped,
    EntityStateToJSON,
} from './EntityState';

/**
 * 
 * @export
 * @interface CampaignScheduleFilter
 */
export interface CampaignScheduleFilter {
    /**
     * 
     * @type {Date}
     * @memberof CampaignScheduleFilter
     */
    fromTs?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CampaignScheduleFilter
     */
    toTs?: Date;
    /**
     * 
     * @type {CampaignType}
     * @memberof CampaignScheduleFilter
     */
    type?: CampaignType;
    /**
     * 
     * @type {CampaignManagement}
     * @memberof CampaignScheduleFilter
     */
    management?: CampaignManagement;
    /**
     * 
     * @type {EntityState}
     * @memberof CampaignScheduleFilter
     */
    state?: EntityState;
    /**
     * 
     * @type {string}
     * @memberof CampaignScheduleFilter
     */
    searchAttribute?: string;
    /**
     * 
     * @type {Array<EntityState>}
     * @memberof CampaignScheduleFilter
     */
    includeStates?: Array<EntityState>;
    /**
     * 
     * @type {Array<EntityState>}
     * @memberof CampaignScheduleFilter
     */
    excludeStates?: Array<EntityState>;
    /**
     * 
     * @type {Array<CampaignType>}
     * @memberof CampaignScheduleFilter
     */
    includeTypes?: Array<CampaignType>;
    /**
     * 
     * @type {Array<CampaignType>}
     * @memberof CampaignScheduleFilter
     */
    excludeTypes?: Array<CampaignType>;
    /**
     * 
     * @type {Array<CampaignManagement>}
     * @memberof CampaignScheduleFilter
     */
    includeManagements?: Array<CampaignManagement>;
    /**
     * 
     * @type {Array<CampaignManagement>}
     * @memberof CampaignScheduleFilter
     */
    excludeManagements?: Array<CampaignManagement>;
}

/**
 * Check if a given object implements the CampaignScheduleFilter interface.
 */
export function instanceOfCampaignScheduleFilter(value: object): boolean {
    return true;
}

export function CampaignScheduleFilterFromJSON(json: any): CampaignScheduleFilter {
    return CampaignScheduleFilterFromJSONTyped(json, false);
}

export function CampaignScheduleFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignScheduleFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'fromTs': json['fromTs'] == null ? undefined : (new Date(json['fromTs'])),
        'toTs': json['toTs'] == null ? undefined : (new Date(json['toTs'])),
        'type': json['type'] == null ? undefined : CampaignTypeFromJSON(json['type']),
        'management': json['management'] == null ? undefined : CampaignManagementFromJSON(json['management']),
        'state': json['state'] == null ? undefined : EntityStateFromJSON(json['state']),
        'searchAttribute': json['searchAttribute'] == null ? undefined : json['searchAttribute'],
        'includeStates': json['includeStates'] == null ? undefined : ((json['includeStates'] as Array<any>).map(EntityStateFromJSON)),
        'excludeStates': json['excludeStates'] == null ? undefined : ((json['excludeStates'] as Array<any>).map(EntityStateFromJSON)),
        'includeTypes': json['includeTypes'] == null ? undefined : ((json['includeTypes'] as Array<any>).map(CampaignTypeFromJSON)),
        'excludeTypes': json['excludeTypes'] == null ? undefined : ((json['excludeTypes'] as Array<any>).map(CampaignTypeFromJSON)),
        'includeManagements': json['includeManagements'] == null ? undefined : ((json['includeManagements'] as Array<any>).map(CampaignManagementFromJSON)),
        'excludeManagements': json['excludeManagements'] == null ? undefined : ((json['excludeManagements'] as Array<any>).map(CampaignManagementFromJSON)),
    };
}

export function CampaignScheduleFilterToJSON(value?: CampaignScheduleFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fromTs': value['fromTs'] == null ? undefined : ((value['fromTs']).toISOString()),
        'toTs': value['toTs'] == null ? undefined : ((value['toTs']).toISOString()),
        'type': CampaignTypeToJSON(value['type']),
        'management': CampaignManagementToJSON(value['management']),
        'state': EntityStateToJSON(value['state']),
        'searchAttribute': value['searchAttribute'],
        'includeStates': value['includeStates'] == null ? undefined : ((value['includeStates'] as Array<any>).map(EntityStateToJSON)),
        'excludeStates': value['excludeStates'] == null ? undefined : ((value['excludeStates'] as Array<any>).map(EntityStateToJSON)),
        'includeTypes': value['includeTypes'] == null ? undefined : ((value['includeTypes'] as Array<any>).map(CampaignTypeToJSON)),
        'excludeTypes': value['excludeTypes'] == null ? undefined : ((value['excludeTypes'] as Array<any>).map(CampaignTypeToJSON)),
        'includeManagements': value['includeManagements'] == null ? undefined : ((value['includeManagements'] as Array<any>).map(CampaignManagementToJSON)),
        'excludeManagements': value['excludeManagements'] == null ? undefined : ((value['excludeManagements'] as Array<any>).map(CampaignManagementToJSON)),
    };
}

