/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtsType } from './DtsType';
import {
    DtsTypeFromJSON,
    DtsTypeFromJSONTyped,
    DtsTypeToJSON,
} from './DtsType';
import type { EntityState } from './EntityState';
import {
    EntityStateFromJSON,
    EntityStateFromJSONTyped,
    EntityStateToJSON,
} from './EntityState';

/**
 * 
 * @export
 * @interface DtsTemplateVO
 */
export interface DtsTemplateVO {
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    description?: string;
    /**
     * 
     * @type {EntityState}
     * @memberof DtsTemplateVO
     */
    state?: EntityState;
    /**
     * 
     * @type {Array<EntityState>}
     * @memberof DtsTemplateVO
     */
    allowedTransitionStates?: Array<EntityState>;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    name?: string;
    /**
     * 
     * @type {DtsType}
     * @memberof DtsTemplateVO
     */
    type?: DtsType;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateVO
     */
    yaml?: string;
    /**
     * 
     * @type {Date}
     * @memberof DtsTemplateVO
     */
    createdTs?: Date;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof DtsTemplateVO
     */
    defaultDeploymentConfig?: { [key: string]: string; };
}

/**
 * Check if a given object implements the DtsTemplateVO interface.
 */
export function instanceOfDtsTemplateVO(value: object): boolean {
    return true;
}

export function DtsTemplateVOFromJSON(json: any): DtsTemplateVO {
    return DtsTemplateVOFromJSONTyped(json, false);
}

export function DtsTemplateVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtsTemplateVO {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'state': json['state'] == null ? undefined : EntityStateFromJSON(json['state']),
        'allowedTransitionStates': json['allowedTransitionStates'] == null ? undefined : ((json['allowedTransitionStates'] as Array<any>).map(EntityStateFromJSON)),
        'label': json['label'] == null ? undefined : json['label'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : DtsTypeFromJSON(json['type']),
        'yaml': json['yaml'] == null ? undefined : json['yaml'],
        'createdTs': json['createdTs'] == null ? undefined : (new Date(json['createdTs'])),
        'defaultDeploymentConfig': json['defaultDeploymentConfig'] == null ? undefined : json['defaultDeploymentConfig'],
    };
}

export function DtsTemplateVOToJSON(value?: DtsTemplateVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'state': EntityStateToJSON(value['state']),
        'allowedTransitionStates': value['allowedTransitionStates'] == null ? undefined : ((value['allowedTransitionStates'] as Array<any>).map(EntityStateToJSON)),
        'label': value['label'],
        'id': value['id'],
        'name': value['name'],
        'type': DtsTypeToJSON(value['type']),
        'yaml': value['yaml'],
        'createdTs': value['createdTs'] == null ? undefined : ((value['createdTs']).toISOString()),
        'defaultDeploymentConfig': value['defaultDeploymentConfig'],
    };
}

