/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DtsType = {
    ConversationalService: 'CONVERSATIONAL_SERVICE',
    SocialChannel: 'SOCIAL_CHANNEL'
} as const;
export type DtsType = typeof DtsType[keyof typeof DtsType];


export function instanceOfDtsType(value: any): boolean {
    return Object.values(DtsType).includes(value);
}

export function DtsTypeFromJSON(json: any): DtsType {
    return DtsTypeFromJSONTyped(json, false);
}

export function DtsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtsType {
    return json as DtsType;
}

export function DtsTypeToJSON(value?: DtsType | null): any {
    return value as any;
}

