/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityState } from './EntityState';
import {
    EntityStateFromJSON,
    EntityStateFromJSONTyped,
    EntityStateToJSON,
} from './EntityState';

/**
 * 
 * @export
 * @interface DtsTemplateFilter
 */
export interface DtsTemplateFilter {
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateFilter
     */
    name?: string;
    /**
     * 
     * @type {EntityState}
     * @memberof DtsTemplateFilter
     */
    state?: EntityState;
    /**
     * 
     * @type {boolean}
     * @memberof DtsTemplateFilter
     */
    showDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DtsTemplateFilter
     */
    searchAttribute?: string;
    /**
     * 
     * @type {Array<EntityState>}
     * @memberof DtsTemplateFilter
     */
    includeStates?: Array<EntityState>;
    /**
     * 
     * @type {Array<EntityState>}
     * @memberof DtsTemplateFilter
     */
    excludeStates?: Array<EntityState>;
}

/**
 * Check if a given object implements the DtsTemplateFilter interface.
 */
export function instanceOfDtsTemplateFilter(value: object): boolean {
    return true;
}

export function DtsTemplateFilterFromJSON(json: any): DtsTemplateFilter {
    return DtsTemplateFilterFromJSONTyped(json, false);
}

export function DtsTemplateFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtsTemplateFilter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'state': json['state'] == null ? undefined : EntityStateFromJSON(json['state']),
        'showDeleted': json['showDeleted'] == null ? undefined : json['showDeleted'],
        'searchAttribute': json['searchAttribute'] == null ? undefined : json['searchAttribute'],
        'includeStates': json['includeStates'] == null ? undefined : ((json['includeStates'] as Array<any>).map(EntityStateFromJSON)),
        'excludeStates': json['excludeStates'] == null ? undefined : ((json['excludeStates'] as Array<any>).map(EntityStateFromJSON)),
    };
}

export function DtsTemplateFilterToJSON(value?: DtsTemplateFilter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'state': EntityStateToJSON(value['state']),
        'showDeleted': value['showDeleted'],
        'searchAttribute': value['searchAttribute'],
        'includeStates': value['includeStates'] == null ? undefined : ((value['includeStates'] as Array<any>).map(EntityStateToJSON)),
        'excludeStates': value['excludeStates'] == null ? undefined : ((value['excludeStates'] as Array<any>).map(EntityStateToJSON)),
    };
}

