/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Kpi } from './Kpi';
import {
    KpiFromJSON,
    KpiFromJSONTyped,
    KpiToJSON,
} from './Kpi';
import type { StatResultType } from './StatResultType';
import {
    StatResultTypeFromJSON,
    StatResultTypeFromJSONTyped,
    StatResultTypeToJSON,
} from './StatResultType';

/**
 * 
 * @export
 * @interface GetCompareStatViewRequest
 */
export interface GetCompareStatViewRequest {
    /**
     * 
     * @type {Date}
     * @memberof GetCompareStatViewRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetCompareStatViewRequest
     */
    to?: Date;
    /**
     * 
     * @type {Array<Kpi>}
     * @memberof GetCompareStatViewRequest
     */
    kpis?: Array<Kpi>;
    /**
     * 
     * @type {StatResultType}
     * @memberof GetCompareStatViewRequest
     */
    statResultType?: StatResultType;
}

/**
 * Check if a given object implements the GetCompareStatViewRequest interface.
 */
export function instanceOfGetCompareStatViewRequest(value: object): boolean {
    return true;
}

export function GetCompareStatViewRequestFromJSON(json: any): GetCompareStatViewRequest {
    return GetCompareStatViewRequestFromJSONTyped(json, false);
}

export function GetCompareStatViewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCompareStatViewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'kpis': json['kpis'] == null ? undefined : ((json['kpis'] as Array<any>).map(KpiFromJSON)),
        'statResultType': json['statResultType'] == null ? undefined : StatResultTypeFromJSON(json['statResultType']),
    };
}

export function GetCompareStatViewRequestToJSON(value?: GetCompareStatViewRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'kpis': value['kpis'] == null ? undefined : ((value['kpis'] as Array<any>).map(KpiToJSON)),
        'statResultType': StatResultTypeToJSON(value['statResultType']),
    };
}

