/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatEnum } from './StatEnum';
import {
    StatEnumFromJSON,
    StatEnumFromJSONTyped,
    StatEnumToJSON,
} from './StatEnum';
import type { StatResultType } from './StatResultType';
import {
    StatResultTypeFromJSON,
    StatResultTypeFromJSONTyped,
    StatResultTypeToJSON,
} from './StatResultType';

/**
 * 
 * @export
 * @interface GetStatViewRequest
 */
export interface GetStatViewRequest {
    /**
     * 
     * @type {Date}
     * @memberof GetStatViewRequest
     */
    from?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetStatViewRequest
     */
    to?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetStatViewRequest
     */
    entityIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof GetStatViewRequest
     */
    statClass?: string;
    /**
     * 
     * @type {StatResultType}
     * @memberof GetStatViewRequest
     */
    statResultType?: StatResultType;
    /**
     * 
     * @type {Array<StatEnum>}
     * @memberof GetStatViewRequest
     */
    statEnums?: Array<StatEnum>;
}

/**
 * Check if a given object implements the GetStatViewRequest interface.
 */
export function instanceOfGetStatViewRequest(value: object): boolean {
    return true;
}

export function GetStatViewRequestFromJSON(json: any): GetStatViewRequest {
    return GetStatViewRequestFromJSONTyped(json, false);
}

export function GetStatViewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatViewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'] == null ? undefined : (new Date(json['from'])),
        'to': json['to'] == null ? undefined : (new Date(json['to'])),
        'entityIds': json['entityIds'] == null ? undefined : json['entityIds'],
        'statClass': json['statClass'] == null ? undefined : json['statClass'],
        'statResultType': json['statResultType'] == null ? undefined : StatResultTypeFromJSON(json['statResultType']),
        'statEnums': json['statEnums'] == null ? undefined : ((json['statEnums'] as Array<any>).map(StatEnumFromJSON)),
    };
}

export function GetStatViewRequestToJSON(value?: GetStatViewRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'] == null ? undefined : ((value['from']).toISOString()),
        'to': value['to'] == null ? undefined : ((value['to']).toISOString()),
        'entityIds': value['entityIds'],
        'statClass': value['statClass'],
        'statResultType': StatResultTypeToJSON(value['statResultType']),
        'statEnums': value['statEnums'] == null ? undefined : ((value['statEnums'] as Array<any>).map(StatEnumToJSON)),
    };
}

