/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatEnum } from './StatEnum';
import {
    StatEnumFromJSON,
    StatEnumFromJSONTyped,
    StatEnumToJSON,
} from './StatEnum';

/**
 * 
 * @export
 * @interface Kpi
 */
export interface Kpi {
    /**
     * 
     * @type {string}
     * @memberof Kpi
     */
    entityId?: string;
    /**
     * 
     * @type {number}
     * @memberof Kpi
     */
    entityFk?: number;
    /**
     * 
     * @type {string}
     * @memberof Kpi
     */
    entityClass?: string;
    /**
     * 
     * @type {string}
     * @memberof Kpi
     */
    label?: string;
    /**
     * 
     * @type {StatEnum}
     * @memberof Kpi
     */
    stat?: StatEnum;
    /**
     * 
     * @type {string}
     * @memberof Kpi
     */
    type?: string;
}

/**
 * Check if a given object implements the Kpi interface.
 */
export function instanceOfKpi(value: object): boolean {
    return true;
}

export function KpiFromJSON(json: any): Kpi {
    return KpiFromJSONTyped(json, false);
}

export function KpiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Kpi {
    if (json == null) {
        return json;
    }
    return {
        
        'entityId': json['entityId'] == null ? undefined : json['entityId'],
        'entityFk': json['entityFk'] == null ? undefined : json['entityFk'],
        'entityClass': json['entityClass'] == null ? undefined : json['entityClass'],
        'label': json['label'] == null ? undefined : json['label'],
        'stat': json['stat'] == null ? undefined : StatEnumFromJSON(json['stat']),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function KpiToJSON(value?: Kpi | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'entityId': value['entityId'],
        'entityFk': value['entityFk'],
        'entityClass': value['entityClass'],
        'label': value['label'],
        'stat': StatEnumToJSON(value['stat']),
        'type': value['type'],
    };
}

