/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParameterVO
 */
export interface ParameterVO {
    /**
     * 
     * @type {string}
     * @memberof ParameterVO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterVO
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterVO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterVO
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof ParameterVO
     */
    description?: string;
}

/**
 * Check if a given object implements the ParameterVO interface.
 */
export function instanceOfParameterVO(value: object): boolean {
    return true;
}

export function ParameterVOFromJSON(json: any): ParameterVO {
    return ParameterVOFromJSONTyped(json, false);
}

export function ParameterVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParameterVO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
        'type': json['type'] == null ? undefined : json['type'],
        'label': json['label'] == null ? undefined : json['label'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ParameterVOToJSON(value?: ParameterVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'value': value['value'],
        'type': value['type'],
        'label': value['label'],
        'description': value['description'],
    };
}

