/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatEnum
 */
export interface StatEnum {
    /**
     * 
     * @type {number}
     * @memberof StatEnum
     */
    index?: number;
    /**
     * 
     * @type {string}
     * @memberof StatEnum
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof StatEnum
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof StatEnum
     */
    description?: string;
}

/**
 * Check if a given object implements the StatEnum interface.
 */
export function instanceOfStatEnum(value: object): boolean {
    return true;
}

export function StatEnumFromJSON(json: any): StatEnum {
    return StatEnumFromJSONTyped(json, false);
}

export function StatEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatEnum {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'] == null ? undefined : json['index'],
        'label': json['label'] == null ? undefined : json['label'],
        'value': json['value'] == null ? undefined : json['value'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function StatEnumToJSON(value?: StatEnum | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'index': value['index'],
        'label': value['label'],
        'value': value['value'],
        'description': value['description'],
    };
}

