/* tslint:disable */
/* eslint-disable */
/**
 * dashboard-backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UIAction = {
    View: 'VIEW',
    Edit: 'EDIT'
} as const;
export type UIAction = typeof UIAction[keyof typeof UIAction];


export function instanceOfUIAction(value: any): boolean {
    return Object.values(UIAction).includes(value);
}

export function UIActionFromJSON(json: any): UIAction {
    return UIActionFromJSONTyped(json, false);
}

export function UIActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UIAction {
    return json as UIAction;
}

export function UIActionToJSON(value?: UIAction | null): any {
    return value as any;
}

